### ISSUE TITLE
Unable to launch after installation on Win11

### ISSUE THREAD

**Issue by Soltus** [GyulyVGC/sniffnet#152]
![image](https://user-images.githubusercontent.com/83791825/232266835-cb564a82-1769-4183-9b88-695c21674887.png)
missing wpcap.dll
When I try to install WinPcap.exe, I reopen it and receive a new error message
![image](https://user-images.githubusercontent.com/83791825/232266923-6c045780-c7be-47cd-bcc2-d96019eb4b07.png)

**Comment by GyulyVGC** [comment]
I suggest you to use npcap instead of winpcap, as described in the "Required dependencies section" of Sniffnet README.
Moreover you also have to install npcap SDK and configure your LIB environment variable:

![Screenshot 2023-04-16 at 08 23 53](https://user-images.githubusercontent.com/100347457/232276626-78a21882-651e-4a88-a47a-38ffe6bc1dff.png)

**Comment by Soltus** [comment]
thanks
