### ISSUE TITLE
GRAPHICS CREATION FAILED

### ISSUE THREAD

**Issue by ParkerStones** [GyulyVGC/sniffnet#260]
_Using
Ubuntu 22.04.2 LTS
Kernel 5.19.0-43 generic
Running Wayland not X
Core i5 3rd Gen with Intel HD Graphics (no dedicated GPU)_

**Running Sniffnet gives Graphics Adapter not Found ERROR**
![Screenshot from 2023-06-08 18-32-25](https://github.com/GyulyVGC/sniffnet/assets/38376474/a18c7287-5e87-430c-bdd8-7be9d93fc7d0)

**Comment by 4r7if3x** [comment]
The first set of Errors suggests that your system is not using UTF-8 encoded locales. You can check this by running the `locale` command and you should be able to see the language code in every setting has a `.UTF-8` suffix. Otherwise, you can reconfigure it manually:

```
sudo dpkg-reconfigure locales
```

Regarding the last error, are you running Sniffnet with escalated privileges (e.g. `root`)?

**Comment by ParkerStones** [comment]
**HERE IT IS !!**
![Screenshot from 2023-06-09 00-34-16](https://github.com/GyulyVGC/sniffnet/assets/38376474/3ec678ed-54e5-4c1c-aa71-56de3e285b08)

**Comment by 4r7if3x** [comment]
@ParkerStones I asked the question because you don't need to run it with escalated privileges and sometimes when you do (and in that case, you need to also pass the environment variables using `sudo -E`), that can cause the Graphics issue on _Wayland_, although, that's often reported on _Nvidia_ chips.

So if you run the program with a non-root user and still get the same Graphics error, that usually would be an issue with your graphic driver.

**Comment by ParkerStones** [comment]
> @ParkerStones I asked the question because you don't need to run it with escalated privileges and sometimes when you do (and in that case, you need to also pass the environment variables using `sudo -E`), that can cause the Graphics issue on _Wayland_, although, that's often reported on _Nvidia_ chips.
> 
> So if you run the program with a non-root user and still get the same Graphics error, that usually would be an issue with your graphic driver.

Oh !!........so that means until that driver bug is patched for my hardware it will be impossible for me to use the program!!........
SED
i want to use this tool 🥲......

**Comment by 4r7if3x** [comment]
@ParkerStones Sorry, I don't know more about this, but I believe you can search for a solution on the web or temporarily switch to `Xorg`.

**Comment by GyulyVGC** [comment]
We can try giving you an alternative version using another graphical renderer.
I will come back to you soon. @ParkerStones

**Comment by GyulyVGC** [comment]
@ParkerStones 

Here you are:

[Sniffnet_LinuxDEB_amd64.deb.zip](https://github.com/GyulyVGC/sniffnet/files/11693023/Sniffnet_LinuxDEB_amd64.deb.zip)

Let me know if it solves the issue 🤞

**Comment by ParkerStones** [comment]
> @ParkerStones Sorry, I don't know more about this, but I believe you can search for a solution on the web or temporarily 
switch to `Xorg`.

@4r7if3x **Nope Not Working on Xorg Either**
 _SEE HERE_
![Screenshot from 2023-06-09 07-30-52](https://github.com/GyulyVGC/sniffnet/assets/38376474/5489e1be-7766-4b49-9f4c-5021b595e71b)

**Comment by ParkerStones** [comment]
> @ParkerStones
> 
> Here you are:
> 
> [Sniffnet_LinuxDEB_amd64.deb.zip](https://github.com/GyulyVGC/sniffnet/files/11693023/Sniffnet_LinuxDEB_amd64.deb.zip)
> 
> Let me know if it solves the issue crossed_fingers

**Its WORKING SIR**
Thank You..........
![Screenshot from 2023-06-09 07-34-42](https://github.com/GyulyVGC/sniffnet/assets/38376474/be56b170-0cdc-42ad-bb33-554f9b144e5b)
 

also Thanks @4r7if3x for your valuable support too hermano !!

**Comment by GyulyVGC** [comment]
AMAZINGGG 🎉🎉

Happy use of Sniffnet!
