### ISSUE TITLE
libpcap error: socket: Operation not permitted

### ISSUE THREAD

**Issue by Aloso** [GyulyVGC/sniffnet#263]
**Describe the bug**
This is shown after selecting a network adapter and pressing "Start", if `sniffnet` is executed without `sudo`:

![image](https://github.com/GyulyVGC/sniffnet/assets/15658558/3907e789-f97a-45d9-8d86-524cbf20a1f7)

**To Reproduce**
1. Install sniffnet via `cargo install sniffnet`
2. Run `sniffnet` in the terminal
3. Select a network adapter and press "Start"

**Expected behavior**
Sniffnet should work without `sudo`.

Note that the Arch Linux package (installed with `pacman -S sniffnet`) worked without `sudo`, but is currently outdated (at version 1.2.0).

**Desktop (please complete the following information):**
 - OS: Manjaro 23.0.0 UltimaThule
 - Kernel: x86_64 Linux 6.3.5-1-MANJARO
 - Version 1.2.1 (installed with `cargo install`)

**Comment by Aloso** [comment]
Additional problems:

- The error message is not selectable, so it can't be easily copy+pasted
- The error message is not actionable (there's no information about how to fix it)

**Comment by GyulyVGC** [comment]
Just execute this command and you should be ok with the libpcap error:

```sh
sudo setcap cap_net_raw,cap_net_admin=eip <your/Sniffnet/executable/path>
```

**Comment by GyulyVGC** [comment]
> * The error message is not selectable, so it can't be easily copy+pasted

This has to do with the library I use for the GUI, which doesn't support yet copying text

> * The error message is not actionable (there's no information about how to fix it)

There are various errors that can be raised and they come from the underlying libpcap library and I currently don't check which specific error is returned (also because the solution is specific to the OS). 
However, this case is documented and the README recommend to use the command I provided you 👍 

Let me know if you solve the issue

**Comment by Aloso** [comment]
Closing since this is documented
