### ISSUE TITLE
Simpler logo

### ISSUE THREAD

**Issue by Aloso** [GyulyVGC/sniffnet#274]
**Is your feature request related to a problem? Please describe.**
Having a simpler logo has many advantages. First, the logo is recognizable even at small sizes, like the favicon in browser tabs (16x16 pixels on typical screens), the icon in OS windows, etc.

Second, simple logos appear modern, while more detailed logos may feel outdated. 

Third, simpler icons are easier to memorize and recognize. For example, everyone knows what the Facebook or Twitter logo look like. And here's how the Firefox logo has evolved:

![image](https://github.com/GyulyVGC/sniffnet/assets/15658558/49e37e5a-150c-465c-84a5-eef792a98454)

Since 2013, the logo has become progressively simpler: Many details were removed, but it's still easily recognizable, and looks great at every size.

**Describe the solution you'd like**
Here's the current sniffnet logo, and two simplified versions I made:

![grafik](https://github.com/GyulyVGC/sniffnet/assets/15658558/7fff21a7-6fff-423b-bbf0-69ee02b1f1c2)

I think the simpler versions look much better, especially in the small resolution. What do you think?

<details>

<summary><b>Click to see SVG versions</b></summary>

![glyph-new](https://github.com/GyulyVGC/sniffnet/assets/15658558/1c9061c9-a51a-453b-ba0c-56da1ab8db01)

![glyph-new-solid](https://github.com/GyulyVGC/sniffnet/assets/15658558/a9c828bb-04cd-4ce6-a32e-1f5f8d678ae9)

</details>

**Comment by vtonu** [comment]
I agree that the current logo is not the best. However, with the way you described how it could be, that just looks like every other "spy" or "hacker" tool symbol, especially when its just black and white. Can you actually replicate the full logo, because I love the current red and blue background, so seeing this new SVG you created on top of those colors would describe your enhancement better. I personally like the current colors, though the details are a bit too much.

**Comment by GyulyVGC** [comment]
Version 1.3 will be released next, and I think this is can finally be the occasion to create a new logo based on the idea of this issue.

Hey @Aloso what did you use to draw the SVGs? I like their style and I was thinking about creating something similar to discuss with you.
Since I'm not an expert in the field (the current logo is designed with Image Preview of macOS 😳) I wanted to know if tools like [this](https://editor.method.ac) are the way to go.

**Comment by GyulyVGC** [comment]
Boom #464 

Feel free to leave comments!
