### ISSUE TITLE
Interface glitches

### ISSUE THREAD

**Issue by ethandudu** [GyulyVGC/sniffnet#275]
**Describe the bug**
When I launch the app, the interface seems to be glitched (see the video below)

**To Reproduce**
Describe steps to reproduce the bug, e.g.:
1. Start Sniffnet

**Expected behavior**
Smooth interface

**Screenshots**
![image](https://github.com/GyulyVGC/sniffnet/assets/41381482/06450f0c-6e66-4b40-af1f-8f72c786a6f4)

https://github.com/GyulyVGC/sniffnet/assets/41381482/abb20d1a-6943-4da2-a41e-6d536090ebf8

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version 1.2.1

**Additional context**
Fresh install of Sniffnet and NpCap

**Comment by ethandudu** [comment]
Fixed with #218

**Comment by GyulyVGC** [comment]
Hi @ethandudu 

This problem occur because you graphical adapter is not compatible with the default renderer used.
Here you are for you a version of the app using an alternative renderer, which usually solves this kind of problems:

[Sniffnet_Windows_64-bit.msi.zip](https://github.com/GyulyVGC/sniffnet/files/11728406/Sniffnet_Windows_64-bit.msi.zip)

EDIT: even if you already solved the problem, this one contains the latest version of the app (v1.2.1)

**Comment by GyulyVGC** [comment]
Hi @ethandudu!
I'm coming back to you since recently Iced has finally overcome the limitations due to the graphical renderers and is now able to use a different renderer at runtime if the default one crashes.
The alternative renderer is tiny-skia, a CPU-only renderer that should run everywhere.

In the following you can find a link to a version of Sniffnet based on the latest Iced release.
In your case the default renderer didn't crash but the problem was only related to screen glitching... so I don't know if it's solved in this specific case...
It'd be awesome if you could kindly try it and let me know if everything is correctly displayed 🤞

https://github.com/GyulyVGC/sniffnet/suites/14755797018/artifacts/838922230

**Comment by ethandudu** [comment]
Hi @GyulyVGC !

I've just installed the latest version and I'm happy to inform you that the screen glitching problem is no longer a problem !

**Comment by ethandudu** [comment]
There it is !
![image](https://github.com/GyulyVGC/sniffnet/assets/41381482/51b53fe7-b3c0-4261-8da4-e738a5b7979c)

**Comment by GyulyVGC** [comment]
Well, it seems to be wgpu in fact...
This means that it still uses the default renderer but this time without glitches.
Maybe they improved something also about wgpu then.

Thanks again 🙌
