### ISSUE TITLE
GraphicsAdapterNotFound

### ISSUE THREAD

**Issue by nobicycle** [GyulyVGC/sniffnet#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

```
$ XDG_RUNTIME_DIR=/run/user/$UID sniffnet
Error: GraphicsCreationFailed(GraphicsAdapterNotFound)

```
```
$ uname -a
Linux tower 6.1.31-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023 x86_64 GNU/Linux

Version sniffnet 1.2.0 and 1.2.1
```
This is related bt closed
https://github.com/GyulyVGC/sniffnet/issues/260

### How did you install the app?

downloaded one of the provided packages

### Operating System

Linux

**Comment by GyulyVGC** [comment]
Hi @nobicycle 
This is because your graphical adapter is incompatible with the default renderer used by the GUI library, as stated in other issues.

Are you able to open deb or rpm packages? If so I can provide you a version of the app using a different graphical renderer.
If you are not able to open them, unluckily the Arch package is only built with the default renderer and the only solution for you would be to build locally from the [`glow-renderer`](https://github.com/GyulyVGC/sniffnet/tree/glow-renderer) branch.

**Comment by nobicycle** [comment]
> Hi @nobicycle This is because your graphical adapter is incompatible with the default renderer used by the GUI library, as stated in other issues.
> 
> Are you able to open deb or rpm packages? If so I can provide you a version of the app using a different graphical renderer. If you are not able to open them, unluckily the Arch package is only built with the default renderer and the only solution for you would be to build locally from the [`glow-renderer`](https://github.com/GyulyVGC/sniffnet/tree/glow-renderer) branch.

Thanks.  RPM is best for me.

**Comment by GyulyVGC** [comment]
@nobicycle here you are: https://github.com/GyulyVGC/sniffnet/suites/13469079922/artifacts/739158258

Let me know!

**Comment by GyulyVGC** [comment]
News?

**Comment by thaihugo** [comment]
Hi,
I don't want to open a duplicate issue, but I have the same problem on a Raspberry pi4 with ARM64 architecture.
Looking at the iced library, it seems graphic support for exotic graphic cards or opengl support is a long way. As I've seen you added more platforms to the github release page, may I ask for a glow based renderer version for linux ARM64 ? I will definitely test and report fully in this thread the result.

**Comment by GyulyVGC** [comment]
Here you are @thaihugo 

https://github.com/GyulyVGC/sniffnet/suites/13469079922/artifacts/739158255

I'm not adding it to the release page because Iced should release a new version supporting a new software renderer in a few days.

I hope the problem will be solved for you with the `glow` renderer in the meantime though!

**Comment by thaihugo** [comment]
This is perfectly working and the program can analyze the network. Thanks for the deb files. 
for those interested, the artifact contains all 4 architectures.

**Comment by GyulyVGC** [comment]
Awesome, I suspected it... this problem has been solved a number of times with `glow`, therefore I'm closing the issue.

Thanks for the confirmation 🙌

**Comment by GyulyVGC** [comment]
@nobicycle @thaihugo 
Hi! I'm coming back to you since recently Iced has finally overcome the limitations due to the graphical renderers and is now able to use a different renderer at runtime if the default one crashes.
The alternative renderer is `tiny-skia`, a CPU-only renderer that should run everywhere.

In the following you can find a link to a version of Sniffnet based on the latest Iced release.
It'd be awesome if could kindly try it and let me know if everything is correctly displayed 🤞

https://github.com/GyulyVGC/sniffnet/suites/14755797018/artifacts/838922228

**Comment by thaihugo** [comment]
Hello GyulyVGC,

this version works perfectly on my raspberry Pi. I didn't compare the CPU usage between the two, but this one displays also some nice shadow effects that weren't in the glow version.

**Comment by GyulyVGC** [comment]
Shadows effects have been added by myself and are one of the aesthetic improvements to be released in the next version.

Anyway, thanks for the confirmation.
In this way you'll be able to use the main version of the app without problems 🎉

**Comment by nobicycle** [comment]
latest release fixed it.  Sorry for the delay.
