### ISSUE TITLE
screen flashing everywhere

### ISSUE THREAD

**Issue by swmcl** [GyulyVGC/sniffnet#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

After opened the app, every screen was flashing.

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

### Additional context

My OS is Windows 10 64 bit.

**Comment by GyulyVGC** [comment]
This is due to incompatibilities between your graphical adapter and `wgpu`, the default renderer used by iced.

The problem is usually solved by using an alternative renderer (`glow`).

Here you are the download link for the Windows version of Sniffnet using it: https://github.com/GyulyVGC/sniffnet/suites/13469079922/artifacts/739158257

Let me know if it solves the issue!

**Comment by swmcl** [comment]
Thanks!
The issue was solved by this version!

**Comment by GyulyVGC** [comment]
Hi @swmcl! 
I'm coming back to you since recently Iced has finally overcome the limitations due to the graphical renderers and is now able to use a different renderer at runtime if the default one crashes.
The alternative renderer is tiny-skia, a CPU-only renderer that should run everywhere.

In the following you can find a link to a version of Sniffnet based on the latest Iced release.
In your case the default renderer didn't crash but the problem was only related to screen flashing... so I don't know if it's solved in this specific case...
It'd be awesome if you could kindly try it and let me know if everything is correctly displayed 🤞

https://github.com/GyulyVGC/sniffnet/suites/14755797018/artifacts/838922230

**Comment by DreamUFO** [comment]
windows 10  
CPU: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz 3.30 GHz
RAM: 16G
GPU: InterHD Graphics 4600 ( 112 MB /Dell)

same issue : start window just flash one time, then nothing left. 

solved by both 
https://github.com/GyulyVGC/sniffnet/suites/13469079922/artifacts/739158257
and 
https://github.com/GyulyVGC/sniffnet/suites/14755797018/artifacts/838922230
version

hope can solve this problem in main branch, so we can use the release version.

**Comment by GyulyVGC** [comment]
Hi @DreamUFO 

Unluckily it's something that doesn't depend on Sniffnet itself but on the default render by iced.

I'll keep the tiny-skia branch always up to date at every release so that a working version can always be built from there in case of problems with wgpu.

**Comment by DreamUFO** [comment]
That will be very nice of you, add how to find the **tiny-skia-renderer** version release in your readme.
Or add **tiny-skia-renderer** version release in every **main** version release.

**Comment by GyulyVGC** [comment]
> That will be very nice of you, add how to find the **tiny-skia-renderer** version release in your readme.
> Or add **tiny-skia-renderer** version release in every **main** version release.

Thanks for the suggestion.
I've just updated the README, which now includes download links for the app using `tiny-skia`.
Check the [troubleshooting section](https://github.com/GyulyVGC/sniffnet#troubleshooting); download links will be kept up to date to the latest release.
Do you think it's enough?

**Comment by DreamUFO** [comment]
> > That will be very nice of you, add how to find the **tiny-skia-renderer** version release in your readme.
> > Or add **tiny-skia-renderer** version release in every **main** version release.
> 
> Thanks for the suggestion. I've just updated the README, which now includes download links for the app using `tiny-skia`. Check the [troubleshooting section](https://github.com/GyulyVGC/sniffnet#troubleshooting); download links will be kept up to date to the latest release. Do you think it's enough?

You are so kind, that will be all I need.Thanks again. Meet you in internet,I'm so lucky.

**Comment by GyulyVGC** [comment]
> You are so kind, that will be all I need.Thanks again. Meet you in internet,I'm so lucky.

Don't worry 😁
Have a good day!
