### ISSUE TITLE
sniffnet-glow added to the AUR

### ISSUE THREAD

**Issue by glitsj16** [GyulyVGC/sniffnet#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

As Arch Linux user on older hardware I had to build Sniffnet from the `glow-renderer` branch. I've added [sniffnet-glow](https://aur.archlinux.org/packages/sniffnet-glow) to the AUR so other people can more easily find it.

This is a FYI, the app works fine on my aging laptop. Maybe it can go into the readme, but that's up to you. Let's hope a future `iced` release obliterates the need for all this :).

Thank you for creating and offering Sniffnet to the world!

**Comment by GyulyVGC** [comment]
Thank you very much!
I will take care of distributing the information to users who will incur in issues on Arch.

I didn't add the download links of other packages built with `glow`, so I'll follow the same logic.

And yeah... good news from iced actually: they are about to release a new version which include a new software renderer to be used as fallback in case `wgpu` fails (`glow` will be discarded completely from what I've understood).
I'll ping you when it's ready so that you can test it if you want.

**Comment by GyulyVGC** [comment]
@all-contributors please add @glitsj16 for platform.

**Comment by GyulyVGC** [comment]
Hi @glitsj16! I'm coming back to you since recently Iced has finally overcome the limitations due to the graphical renderers and is now able to use a different renderer at runtime if the default one crashes.
The alternative renderer is `tiny-skia`, a CPU-only renderer that should run everywhere.

You can find the version of Sniffnet based on the latest Iced release on [this branch](https://github.com/GyulyVGC/sniffnet/tree/iced-0.10).
It'd be awesome if could kindly try it and let me know if everything is correctly displayed 🤞

**Comment by glitsj16** [comment]
Hi @GyulyVGC, I've done a build from the iced-0.10 branch and it works very well. Feels very smooth on the old laptop, both on X11 and Wayland. All in all an impressive achievement. I really appreciate your work and I'll retire the [sniffnet-glow](https://aur.archlinux.org/packages/sniffnet-glow) package when this tiny-skia makes it into a new sniffnet release.

Regards!

**Comment by GyulyVGC** [comment]
Thanks for having tried, and for the kind words... means a lot to me 🙌

**Comment by glitsj16** [comment]
FYI, the updated [sniffnet](https://archlinux.org/packages/extra/x86_64/sniffnet/) v1.2.2 hit the Arch Linux extra repository. That effectively makes my [sniffnet-glow](https://aur.archlinux.org/packages/sniffnet-glow) obsolete and I've filed a deletion request.

Regards!

**Comment by GyulyVGC** [comment]
Thank you again!
