### ISSUE TITLE
feature request : upload shown as up, download shown as down

### ISSUE THREAD

**Issue by haroldcarr** [GyulyVGC/sniffnet#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

Right now downloads show as upward parts of the graph and uploads show downward (just like Mac Activity Monitor).

Make it configurable so down and be down and up can be up.

### Is your feature request related to a problem?

no

**Comment by GyulyVGC** [comment]
Originally, I chose to display data in this way because usually the upward part of a chart has positive units (incoming), while the downward part of a chart has negative units (outgoing).
Activity Monitor from macOS does the same, as you noticed, and other software as well follow this logic.

Honestly, I don't see a considerable enhancement in making this a configurable option.
Moreover, it'd be nice to make a sort of convention shared by all the users of Sniffnet.
I think that none of the alternatives is better/worse than the other, but a decision had to be taken.

Thanks anyway for the feedback!
