### ISSUE TITLE
Cut paste capabilities and virustotal links for ip address, domain etc

### ISSUE THREAD

**Issue by lpingree** [GyulyVGC/sniffnet#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

I really like this tool, but the thing I'd love to have is:
- Cut paste of fields (IP address, Ports, Protocols, Domains
- Links auto-populated to virustotal for domains and IP addresses

### Is your feature request related to a problem?

n/A

**Comment by GyulyVGC** [comment]
Hi @lpingree 

Check out https://github.com/GyulyVGC/sniffnet/pull/409 in which I implemented the ability to copy IP addresses to clipboard (the feature is merged into the main branch but will be officially released with the next version of the app).

What do you think about that solution? I think that IP addresses are the most important metric and for this reason are the only to be copyable.

Concerning the use of virustotal.... I don't like the idea of being tied to a specific vendor opening their website.

However, I plan to integrate some "IP reputation" service sooner or later, so that users will be able to see the reputation of an address directly inside the app.

**Comment by GyulyVGC** [comment]
Closing in favour of #514
