### ISSUE TITLE
[Bug] Cannot exit Thumbnail mode on Linux

### ISSUE THREAD

**Issue by matbgn** [GyulyVGC/sniffnet#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

Minimize works but maximize back isn't working.

See vidéo below:

https://github.com/GyulyVGC/sniffnet/assets/13169819/d6cbb6c3-fe04-425b-8fc1-a49a174776be

### How did you install the app?

downloaded one of the provided packages

### Operating System

Linux

**Comment by matbgn** [comment]
Just adding a comment Off-Topic to give you a lot of kudos for the UI refactoring!!! You've done an amazing work. 

PS: note that this issue is non-blocking, so take your time to fix it.

**Comment by GyulyVGC** [comment]
Hey @matbgn thanks so much for the kudos, I really appreciate you like it 😄 

***

### The problem

This annoying issue seems to happen only in some Linux systems, and it's due to the fact that when thumbnail mode is active click events on the window may indicate that the user started grabbing it.

While Windows and macOS correctly distinguish when the user clicked on the "maximise" button, in Linux this action is interpreted as a click to start dragging the thumbnail (some environments require a double click to work, while in other cases as yours it's not possible even with multiple clicks).

***

### Possible solutions

- A possible workaround I can think of is to add a keyboard shortcut to enter/exit thumbnail mode, so users with this issue can simply focus the app window and press the shortcut key to maximise it back
- Since the previous point is not a real solution to the main problem, the best strategy would be to set the drag hook for the window excluding the portion where the "maximise" button is... but I'm currently not aware about how to tell Iced to listen to drag events only for a given portion of the window

**Comment by Digitalone1** [comment]
For what it's worth, it works in Gnome Wayland, but only if I double click on the thumbnail icon.

**Comment by GyulyVGC** [comment]
I've come up with a possible solution for this issue: the drag action is now set to require a double click, so that a single click won't be captured as a drag beginning, thus allowing for it to be correctly identified as a simple button click.
Feel free to let me know your thoughts.

**Comment by matbgn** [comment]
Really really neat solution many thanks :pray:

**Comment by GyulyVGC** [comment]
No problem, my pleasure! 👍
