### ISSUE TITLE
thread 'thread_write_report' panic when run not as root. additionally, it'd be nice to save report file in a fixed location independently from running directory.

### ISSUE THREAD

**Issue by burjui** [GyulyVGC/sniffnet#51]
**Describe the bug**
When run not as root, sniffnet panics even with the capabilities set:
```
thread 'thread_write_report' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /home/burjui/.cargo/registry/src/github.com-1ecc6299db9ec823/sniffnet-1.0.1/src/thread_write_report.rs:36:49
```
Runs just fine under `kdesu`.

**To Reproduce**
```
$ sudo setcap cap_net_raw,cap_net_admin=eip ~/.cargo/bin/sniffnet
$ sniffnet
```
**Desktop:**
Manjaro Linux 22.0.0

**Comment by GyulyVGC** [comment]
If you previously run as root and then you try to run as normal user, it will panic because it tries to overwrite the previously generated report without success: in fact the previously generated report has admin privileges and cannot be overwritten by a normal user.

Delete the report file previously generated and you should be fine.

Let me know if it helps.

**Comment by burjui** [comment]
Oh, makes sense. That's why it suddenly started working after changing current directory in the terminal. Maybe `sniffnet` should write the report under `${HOME}/.local/var`? That's a separate issue though.

**Comment by GyulyVGC** [comment]
Has it something to do with admin privileges? What benefit would this change introduce? Or, are you just asserting that it's not a good standard to generate the report in the current directory?

**Comment by burjui** [comment]
> What benefit would this change introduce?

At least the subject of this issue will become irrelevant. The current behaviour is surprising (not in a good way). Even if I always run `sniffnet` as the same user, it still produces a report in every directory from which I run it. 

> not a good standard to generate the report in the current directory

I certainly think that. Traditional place for things like that is `/var/tmp/<name>/` for daemons (see `man hier` for details), and, logically, for apps that would be `${HOME}/.local/var/tmp/<name>/`.

**Comment by GyulyVGC** [comment]
Thanks for pointing out, I will implement this change in the next release!

**Comment by GyulyVGC** [comment]
Textual report is now saved in a fixed directory, instead of using the directory where the execution was started.

The output is now saved in the same folder containing configuration files storing Sniffnet settings. 
The directory is automatically chosen by [confy](https://docs.rs/confy/0.5.1/confy/) depending on your architecture, and can be seen hovering on the "Open full report" button.
