### ISSUE TITLE
The app was unable to start

### ISSUE THREAD

**Issue by JeremyDufeux** [GyulyVGC/sniffnet#83]
Hello

**Describe the bug**
When program is launch, I've the following erroe: "The application was unable to start correctly (0x00007b)."

**To Reproduce**
Describe steps to reproduce the bug, e.g.:
1. installed Npcap
2. Put Npcap SDK in C:\Program Files\Npcap\SDK
3. Add "LIB" system variable with value: "C:\Program Files\Npcap\SDK\Lib\x64"

**Screenshots**
![Screenshot 2023-02-20 08h37m31s735](https://user-images.githubusercontent.com/1122126/220043328-11351a58-e75c-4579-9b9f-f33878c98854.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2 22621.1265

Thanks in advance for help

**Comment by GyulyVGC** [comment]
You installed the app through the installer, right?
I also read from [here](https://appuals.com/fix-error-0xc00007b-application-was-unable-to-start-correctly/) that it could be due to an anti-virus deleting some DLL.
You can try the solutions proposed in that article.

As a workaround, you could download the app from crates.io, but this requires to install also Rust and the Visual Studio Build Tools.

**Comment by GyulyVGC** [comment]
Closing the issue for inactivity and since issues of this kind has already been solved a number of times.
To see other issue like this, filter by `windows` issue tag.
