### ISSUE TITLE
Chinese translation WIP / 中文翻译仍在处理中

### ISSUE THREAD

**Issue by cxw620** [GyulyVGC/sniffnet#92]
由于 https://github.com/GyulyVGC/sniffnet/pull/89 提到的问题, ~~目前暂未能将含有中文翻译的分支合并到主线.~~ 已合并, 等待发版
Due to the problem that https://github.com/GyulyVGC/sniffnet/pull/89 mentioned, branch `chinese_font_setup` cannot be merge into master branch now.

在等待下一版本时, 有需要的, 可以下载我编译的预览版:  [sniffnet.zip](https://github.com/GyulyVGC/sniffnet/files/10853189/sniffnet.zip), 或自行拉取`chinese_font_setup`编译. 
If necessary, you can download [sniffnet.zip](https://github.com/GyulyVGC/sniffnet/files/10853189/sniffnet.zip), or compile by yourself. 

解压然后直接替换位于`C:\Program Files\sniffnet\bin`处的`sniffnet.exe`文件即可. 
Simply unzip the file and replace `C:\Program Files\sniffnet\bin\sniffnet.exe`.

文件校验:
HASH:
 
MD5 `B196739024FFAE7FF221702B21991B95`
SHA-1 `093A9AAF0DA6BDBB38BD0E7A17FD7A79D95BE44E`

**Comment by GyulyVGC** [comment]
Update: I've merged the `chinese_font_setup` into main.
The new version featuring the Chinese language will be released in the next weeks (it could take up to a month), so feel free to leave this issue open.

**Comment by GyulyVGC** [comment]
Hi @cxw620.
[Today's release](https://github.com/GyulyVGC/sniffnet/releases/tag/v1.1.2) finally introduces the Chinese language, so I think that this issue can be closed.
I made an announcement about the release on the Rust Chinese forum ([link](https://rustcc.cn/article?id=2fa29cfd-82f2-4a61-bb07-b93d175d0401)).

If you could spread the news on other Chinese forums/blogs it'd be awesome, so that more people can benefit of your translation!
